#!/usr/bin/env bash
# p3ta-tricks — weekly source pull + rebuild
#
# Pulls every upstream wiki that backs a source, rebuilds only the ones that
# actually moved, refreshes the nav caches and search index, re-applies the
# local corrections, and prints a ready-to-use commit message.
#
# Usage:
#   ./update.sh                 pull, rebuild what changed, leave the diff staged-ready
#   ./update.sh --force         rebuild every source even if nothing was pulled
#   ./update.sh --pull-only     refresh sources/ and report, no rebuild
#   ./update.sh --commit        also `git commit` the result
#   ./update.sh --commit --push also push to origin
#   ./update.sh --skip-check    rebuild without the fidelity gate (see below)
#   ./update.sh --max-churn N   allow N% of a source's pages to differ (default 15)
#
# sources/ is gitignored — these clones are build inputs, not repo content.
# Clones are shallow (--depth 1); a normal `git pull` cannot fast-forward those,
# so updates are done with fetch + reset --hard.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# ── upstream manifest ────────────────────────────────────────────────────────
# source_id | sources/<dir> | git URL
#
# Only sources that are a straight clone of an upstream repo belong here.
# Everything else under content/processed/ is either hand-written (active-
# directory, cheatsheet, bloodhound edges, misc, breaking-adcs, ...) or scraped
# by a dedicated script (adaptix, churchofmalware), and is NOT regenerated by
# this script — rebuilding those without their inputs would delete them.
MANIFEST=(
  "hacktricks|hacktricks|https://github.com/HackTricks-wiki/hacktricks.git"
  "hacktricks-cloud|hacktricks-cloud|https://github.com/HackTricks-wiki/hacktricks-cloud.git"
  "hacker-recipes|hacker-recipes|https://github.com/ShutdownRepo/The-Hacker-Recipes.git"
  "netexec|netexec-wiki|https://github.com/Pennyw0rth/NetExec-Wiki.git"
  "patt|payloadsallthethings|https://github.com/swisskyrepo/PayloadsAllTheThings.git"
  "internal-att|internalallthethings|https://github.com/swisskyrepo/InternalAllTheThings.git"
  "hardware-att|hardwareallthethings|https://github.com/swisskyrepo/HardwareAllTheThings.git"
  "bloodyad|bloodyad-wiki|https://github.com/CravateRouge/bloodyAD.wiki.git"
  "certipy|certipy-wiki|https://github.com/ly4k/Certipy.wiki.git"
  "ligolo-ng|ligolo-ng-wiki|https://github.com/nicocha30/ligolo-ng.wiki.git"
  "goexec|goexec|https://github.com/FalconOpsLLC/goexec.git"
)

# Sources with processed content but no reproducible build input on this box.
# Listed so their absence from the weekly diff is visible rather than silent.
NOT_AUTOMATED="gtfobins lolbas wadcoms exploitdb adaptix churchofmalware sliver"

FORCE=0; PULL_ONLY=0; DO_COMMIT=0; DO_PUSH=0; SKIP_CHECK=0; MAX_CHURN=15
while [ $# -gt 0 ]; do
  case "$1" in
    --force)      FORCE=1 ;;
    --pull-only)  PULL_ONLY=1 ;;
    --commit)     DO_COMMIT=1 ;;
    --push)       DO_PUSH=1 ;;
    --skip-check) SKIP_CHECK=1 ;;
    --max-churn)  shift; MAX_CHURN="${1:?--max-churn needs a value}" ;;
    -h|--help)    sed -n '2,18p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *)            echo "[!] unknown option: $1"; exit 1 ;;
  esac
  shift
done

# PYTHON=... overrides; otherwise prefer the install.sh venv (Windows git-bash
# lays it out under Scripts/), then fall back to whatever python3 is on PATH
PY="${PYTHON:-}"
for cand in "$PWD/.venv/bin/python3" "$PWD/.venv/Scripts/python.exe" "$(command -v python3 || true)"; do
  [ -n "$PY" ] && break
  [ -x "$cand" ] && PY="$cand"
done
[ -n "$PY" ] || { echo "[!] no python3 — run ./install.sh"; exit 1; }
"$PY" -c "import markdown, pygments" 2>/dev/null || {
  echo "[!] $PY is missing build deps (markdown, pygments) — run ./install.sh"; exit 1; }

mkdir -p sources

# HackTricks ships page paths and image names well past Windows' 260-char
# MAX_PATH, which fails the checkout outright on git-bash. Harmless on Linux.
GIT_OPTS=(-c core.longpaths=true)

# ── pull ─────────────────────────────────────────────────────────────────────
echo "[*] Pulling upstream sources..."
CHANGED=()
for row in "${MANIFEST[@]}"; do
  IFS='|' read -r sid dir url <<< "$row"
  path="sources/$dir"

  if [ ! -d "$path/.git" ]; then
    if [ -d "$path" ] && [ -n "$(ls -A "$path" 2>/dev/null)" ]; then
      echo "    $dir — vendored in-repo, not a clone, skipping"
      continue
    fi
    echo "    $dir — cloning"
    git "${GIT_OPTS[@]}" clone --quiet --depth 1 "$url" "$path"
    CHANGED+=("$sid")
    continue
  fi

  before=$(git -C "$path" rev-parse HEAD)
  branch=$(git -C "$path" rev-parse --abbrev-ref HEAD)
  git "${GIT_OPTS[@]}" -C "$path" fetch --quiet --depth 1 origin "$branch"
  git "${GIT_OPTS[@]}" -C "$path" reset --quiet --hard "origin/$branch"
  after=$(git -C "$path" rev-parse HEAD)

  if [ "$before" != "$after" ]; then
    echo "    $dir — updated ${before:0:7}..${after:0:7}"
    CHANGED+=("$sid")
  else
    echo "    $dir — up to date"
  fi
done

if [ "$FORCE" = 1 ]; then
  CHANGED=()
  for row in "${MANIFEST[@]}"; do
    IFS='|' read -r sid dir _ <<< "$row"
    if [ -d "sources/$dir/.git" ]; then
      CHANGED+=("$sid")
    fi
  done
  echo "[*] --force: rebuilding all ${#CHANGED[@]} cloned sources"
fi

echo "[i] not covered by this script (no build input in repo): $NOT_AUTOMATED"

if [ "$PULL_ONLY" = 1 ]; then
  echo "[+] --pull-only: stopping before rebuild"
  exit 0
fi

if [ ${#CHANGED[@]} -eq 0 ]; then
  echo "[+] Nothing changed upstream. Site is current."
  exit 0
fi

# ── fidelity gate ────────────────────────────────────────────────────────────
# scripts/inject_variable_tokens.py is a reconstruction of a lost original, so
# prove the pipeline still reproduces committed content before letting it write
# over content/. Without this a rebuild silently strips the <TARGET>/<USERNAME>
# placeholders from pages upstream never touched.
if [ "$SKIP_CHECK" = 1 ]; then
  echo "[!] --skip-check: rebuilding without verifying pipeline fidelity"
else
  echo "[*] Checking pipeline fidelity..."
  if ! "$PY" scripts/check_fidelity.py "${CHANGED[@]}" --max-churn "$MAX_CHURN"; then
    echo "[!] Aborting before content/ is touched. Nothing was modified."
    exit 1
  fi
fi

# ── rebuild ──────────────────────────────────────────────────────────────────
echo "[*] Rebuilding content for: ${CHANGED[*]}"
"$PY" scripts/rebuild_sources.py "${CHANGED[@]}"

echo "[*] Refreshing nav caches..."
"$PY" scripts/dump_nav_cache.py "${CHANGED[@]}"

echo "[*] Enhancing search index..."
"$PY" scripts/enhance_search_index.py

# Must run last: rebuild_sources.py regenerates upstream pages from scratch and
# would otherwise reintroduce every upstream bug we have already corrected.
echo "[*] Re-applying local fixes..."
"$PY" scripts/local_fixes.py

# ── report ───────────────────────────────────────────────────────────────────
# paste -sd', ' would cycle through the delimiter's characters ("a,b c,d"),
# so join on a single comma and space it out afterwards
PULLED=$(printf '%s\n' "${CHANGED[@]}" | sort | paste -sd, - | sed 's/,/, /g')
MSG="Weekly site update [$(date +%F)] pulled: $PULLED"

echo
echo "[+] Done. $(git status --porcelain | wc -l) files changed."
echo "    Suggested commit: $MSG"

if [ "$DO_COMMIT" = 1 ]; then
  git add -A content static
  git commit -q -m "$MSG"
  echo "[+] Committed."
  if [ "$DO_PUSH" = 1 ]; then
    git push origin "$(git rev-parse --abbrev-ref HEAD)"
    echo "[+] Pushed."
  fi
fi
