#!/usr/bin/env python3
"""Re-apply local corrections to upstream-derived pages after a rebuild.

Anything under content/processed/ that comes from an upstream repo is thrown
away and regenerated by rebuild_sources.py, so a hand-edit to one of those pages
survives exactly until the next weekly pull. Corrections that should outlive the
pull belong here instead: update.sh runs this as the last build step.

Every rule is idempotent -- running twice is a no-op -- so this is safe to run
on its own at any time.

Currently fixed
---------------
OpenLDAP 2.6 removed the deprecated `-h host` / `-p port` options from every
client tool. Upstream docs still teach `-h`, which now fails outright with
"ldapsearch: unrecognized option" on Kali 2024+, Debian 12+ and Exegol. The
rules below rewrite those to `-H <uri>` and correct the filters and scopes that
were wrong alongside them.

Usage:
    python3 scripts/local_fixes.py              # apply
    python3 scripts/local_fixes.py --dry-run    # report only
"""
import glob
import html
import json
import os
import re
import sys
from pathlib import Path

import markdown as md_lib

ROOT = Path(__file__).resolve().parent.parent

MD_EXTENSIONS = [
    "fenced_code", "tables", "toc", "attr_list", "admonition",
    "pymdownx.superfences", "pymdownx.highlight",
]

BLOCK   = re.compile(r'<div class="highlight">.*?</div>', re.S)
INLINE  = re.compile(r"<code(?:\s[^>]*)?>(.*?)</code>", re.S)
HEADING = re.compile(r"<h([1-6])([^>]*)>(.*?)</h\1>", re.S)
TAG     = re.compile(r"<[^>]+>")
LDAP_TOOL = re.compile(r"\bldap(search|modify|add|delete|passwd|whoami|compare)\b")

# ---------------------------------------------------------------------------
# whole-command rewrites, for the cases where more than the -h flag was wrong
# ---------------------------------------------------------------------------
LINE_REWRITES = [
    # Password policy: `-s sub "*"` is not a valid RFC 4515 filter, and dumping
    # the whole directory to feed `grep -B 10` is a lot of noise for attributes
    # that live on the domain root object. Read them off it directly.
    (
        'ldapsearch -h <dc-ip> -x -b "DC=<DOMAIN>,DC=LOCAL" -s sub "*" | grep -m 1 -B 10 pwdHistoryLength',
        'ldapsearch -H ldap://<dc-ip> -x -b "DC=<DOMAIN>,DC=LOCAL" -s base "(objectClass=*)" minPwdLength pwdHistoryLength lockoutThreshold lockoutDuration maxPwdAge minPwdAge',
    ),
    (
        'ldapsearch -h <dc-ip> -x -b "DC=<domain-name>,DC=LOCAL" -s sub "*" | grep -m 1 -B 10 pwdHistoryLength',
        'ldapsearch -H ldap://<dc-ip> -x -b "DC=<domain-name>,DC=LOCAL" -s base "(objectClass=*)" minPwdLength pwdHistoryLength lockoutThreshold lockoutDuration maxPwdAge minPwdAge',
    ),
    (
        'ldapsearch -h 10.10.10.10 -x -b "DC=DOMAIN_NAME,DC=LOCAL" -s sub "*" | grep -m 1 -B 10 pwdHistoryLength',
        'ldapsearch -H ldap://10.10.10.10 -x -b "DC=DOMAIN_NAME,DC=LOCAL" -s base "(objectClass=*)" minPwdLength pwdHistoryLength lockoutThreshold lockoutDuration maxPwdAge minPwdAge',
    ),
    # User enumeration: the computer class derives from user, so
    # (objectclass=user) also returns every machine account.
    (
        'ldapsearch -h <dc-ip> -x -b "DC=<DOMAIN>,DC=LOCAL" -s sub "(&(objectclass=user))" | grep sAMAccountName: | cut -f2 -d" "',
        'ldapsearch -H ldap://<dc-ip> -x -b "DC=<DOMAIN>,DC=LOCAL" "(&(objectClass=user)(objectCategory=person))" sAMAccountName | grep -i "^sAMAccountName:" | cut -d" " -f2',
    ),
    (
        'ldapsearch -h 172.16.5.5 -x -b "DC=INLANEFREIGHT,DC=LOCAL" -s sub "(&(objectclass=user))"  | grep sAMAccountName: | cut -f2 -d" "',
        'ldapsearch -H ldap://172.16.5.5 -x -b "DC=INLANEFREIGHT,DC=LOCAL" "(&(objectClass=user)(objectCategory=person))" sAMAccountName | grep -i "^sAMAccountName:" | cut -d" " -f2',
    ),
    (
        'ldapsearch -x -b "DC=DOMAIN_NAME,DC=LOCAL" -s sub "(&(objectclass=user))" -h 10.10.10.10 | grep -i samaccountname: | cut -f 2 -d " "',
        'ldapsearch -x -H ldap://10.10.10.10 -b "DC=DOMAIN_NAME,DC=LOCAL" "(&(objectClass=user)(objectCategory=person))" sAMAccountName | grep -i "^sAMAccountName:" | cut -d" " -f2',
    ),
    # InternalAllTheThings LAPS read: upstream lost the -h and -w values to a
    # pair of stray non-breaking spaces, leaving a command that cannot run.
    (
        'ldapsearch -x -h\xa0 -D "<bind user>" -w\xa0 -b "dc=<>,dc=<>,dc=<>" "(&(objectCategory=computer)(ms-MCS-AdmPwd=*))" ms-MCS-AdmPwd',
        'ldapsearch -x -H ldap://<dc-ip> -D "<bind user>" -w "<password>" -b "dc=<>,dc=<>,dc=<>" "(&(objectCategory=computer)(ms-MCS-AdmPwd=*))" ms-MCS-AdmPwd',
    ),
    # The Hacker Recipes lists the pre-2.6 and post-2.6 forms side by side; keep
    # only the one that still works, and use one consistent variable.
    (
        'ldapsearch -h "$DC_IP" -x -s base namingcontexts\nldapsearch -H "ldap://$DC_IP" -x -s base namingcontexts',
        'ldapsearch -H "ldap://$DC_IP" -x -s base namingcontexts',
    ),
    (
        'ldapsearch -h "$DC_IP" -x -b "DC=DOMAIN,DC=LOCAL"\nldapsearch -H "ldap://$TARGET" -x -b "DC=DOMAIN,DC=LOCAL"',
        'ldapsearch -H "ldap://$DC_IP" -x -b "DC=DOMAIN,DC=LOCAL"',
    ),
]

# generic `-h <host>` -> `-H ldap://<host>`, on lines that invoke an LDAP tool
H_BARE   = re.compile(r"(?<= )-h(\s+)(?![-\s])([^\s'\"\\|]+)")
H_DQUOTE = re.compile(r'(?<= )-h(\s+)"([^"]+)"')
H_SQUOTE = re.compile(r"(?<= )-h(\s+)'([^']+)'")


# pages that deliberately show the broken pre-2.6 form to contrast it with the
# working one mark it with this comment; leave those lines alone
KEEP_MARKER = "removed in OpenLDAP"


def _fix_line(line: str) -> str:
    if not LDAP_TOOL.search(line) or KEEP_MARKER in line:
        return line
    line = H_DQUOTE.sub(lambda m: f'-H{m.group(1)}"ldap://{m.group(2)}"', line)
    line = H_SQUOTE.sub(lambda m: f"-H{m.group(1)}'ldap://{m.group(2)}'", line)
    line = H_BARE.sub(lambda m: f"-H{m.group(1)}ldap://{m.group(2)}", line)
    return line


def fix_code(code: str) -> str:
    for old, new in LINE_REWRITES:
        code = code.replace(old, new)
    # a backslash-continued command carries its -h onto a later physical line,
    # so keep the "this is an LDAP command" context across continuations
    out, carry = [], False
    for line in code.split("\n"):
        subject = line if not carry else "ldapsearch " + line
        fixed = _fix_line(subject)
        if carry:
            fixed = fixed[len("ldapsearch "):]
        out.append(fixed)
        carry = line.rstrip().endswith("\\") and (carry or bool(LDAP_TOOL.search(line)))
    return "\n".join(out)


def render_block(code: str) -> str:
    md = md_lib.Markdown(extensions=MD_EXTENSIONS)
    out = md.convert("```bash\n" + code + "\n```")
    m = BLOCK.search(out)
    return m.group(0) if m else out


def _excerpt(page_html: str, n: int = 200) -> str:
    text = re.sub(r"<[^>]+>", " ", page_html)
    return re.sub(r"\s+", " ", text).strip()[:n]


def fix_html(page_html: str):
    changes = 0

    def _block(m):
        nonlocal changes
        raw = m.group(0)
        code = html.unescape(TAG.sub("", raw)).rstrip("\n")
        if not LDAP_TOOL.search(code):
            return raw
        fixed = fix_code(code)
        if fixed == code:
            return raw
        changes += 1
        return render_block(fixed)

    def _inline(m):
        nonlocal changes
        code = html.unescape(m.group(1))
        if not LDAP_TOOL.search(code) or "<span" in m.group(1):
            return m.group(0)
        fixed = fix_code(code)
        if fixed == code:
            return m.group(0)
        changes += 1
        open_tag = m.group(0)[: m.group(0).index(">") + 1]
        return open_tag + html.escape(fixed, quote=False) + "</code>"

    def _heading(m):
        nonlocal changes
        text = html.unescape(m.group(3))
        if not LDAP_TOOL.search(text) or "<" in m.group(3):
            return m.group(0)
        fixed = fix_code(text)
        if fixed == text:
            return m.group(0)
        changes += 1
        # the id= anchor is deliberately left alone so deep links keep working
        return f"<h{m.group(1)}{m.group(2)}>{html.escape(fixed, quote=False)}</h{m.group(1)}>"

    # highlight blocks first: pygments wraps every token in a <span>, and the
    # inline pass must not try to re-handle what those blocks contain
    page_html = BLOCK.sub(_block, page_html)
    page_html = INLINE.sub(_inline, page_html)
    page_html = HEADING.sub(_heading, page_html)
    return page_html, changes


def main():
    dry = "--dry-run" in sys.argv
    touched = []

    for f in glob.glob(str(ROOT / "content/processed/**/*.json"), recursive=True):
        with open(f, encoding="utf-8") as fh:
            data = json.load(fh)
        new_html, n = fix_html(data.get("html", "") or "")
        if not n:
            continue
        data["html"] = new_html
        data["excerpt"] = _excerpt(new_html)
        touched.append((os.path.relpath(f, ROOT).replace(os.sep, "/"), n))
        if not dry:
            with open(f, "w", encoding="utf-8", newline="") as fh:
                fh.write(json.dumps(data, ensure_ascii=False))

    for rel, n in touched:
        print(f"  {n:3d}  {rel}")
    verb = "would be corrected" if dry else "corrected"
    print(f"  {len(touched)} pages {verb}")
    return len(touched)


if __name__ == "__main__":
    main()
